import re
from typing import Dict, Any

# Dictionary for mapping misidentified Thai digits or symbols
THAI_DIGIT_MAP = {
    '๐': '0', '๑': '1', '๒': '2', '๓': '3', '๔': '4',
    '๕': '5', '๖': '6', '๗': '7', '๘': '8', '๙': '9'
}

# Dictionary for fixing common separated (floating) vowels generated by OCR
FLOATING_VOWEL_FIXES = {
    'เ เ': 'แ',
    'ํา': 'ำ',
    'เ◌ีย': 'เีย', # May vary based on OCR behavior
    ' ์': '์',
    ' ่': '่',
    ' ้': '้',
    ' ๊': '๊',
    ' ๋': '๋',
}

def clean_thai_text(text: str) -> str:
    """
    Cleans up common OCR artifacts in Thai language,
    specifically floating vowels and unintended symbol spaces.
    """
    if not text:
        return ""
        
    cleaned_text = text
    
    # Fix floating vowels
    for wrong, right in FLOATING_VOWEL_FIXES.items():
        cleaned_text = cleaned_text.replace(wrong, right)
        
    # Example: Replace consecutive spaces with a single space, except for clear breaks
    cleaned_text = re.sub(r' {2,}', ' ', cleaned_text)
    
    return cleaned_text.strip()


def parse_legal_layer(text: str) -> Dict[str, Any]:
    """
    Experimental function to parse raw OCR text into the defined Layer JSON structure.
    In production, this should be handled directly by prompt-engineering the VLM, 
    but this acts as a fallback parser.
    """
    lines = text.split('\n')
    
    result = {
        "header": "",
        "sections": [],
        "legal_articles": [],
        "explanation": ""
    }
    
    current_section = None
    explanation_buffer = []
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # 1. Detect Header (e.g., "บทที่ 1...", "ส่วนที่ 2...")
        if re.match(r'^(บทที่|ส่วนที่|หมวดที่)\s*\d+', line) and not result["header"]:
            result["header"] = line
            continue
            
        # 2. Detect Legal Articles (e.g., "มาตรา 150")
        article_match = re.search(r'^(มาตรา\s*\d+[ก-ฮ/\-\.]*)', line)
        if article_match:
            # We found an article
            article_no = article_match.group(1)
            content = line[len(article_no):].strip()
            result["legal_articles"].append({
                "article_no": article_no,
                "content": content,
                "law_name": "unknown" # To be inferred or set by context
            })
            continue
            
        # 3. Detect Sections (e.g., "1.1 ขอบเขต...", "ข้อสังเกต")
        if re.match(r'^(\d+\.\d+|[ก-ฮ]\.|ข้อสังเกต|คำอธิบาย)', line):
            current_section = {"title": line, "body": ""}
            result["sections"].append(current_section)
            continue
            
        # 4. Content population
        if current_section:
            current_section["body"] += line + " "
        else:
            explanation_buffer.append(line)
            
    # Compile any leftover text into explanation
    if explanation_buffer:
        result["explanation"] = " ".join(explanation_buffer).strip()
        
    return result

if __name__ == "__main__":
    # Test the parser
    sample_ocr = \"\"\"
บทที่ 1 นิติกรรม
มาตรา 149 นิติกรรม หมายความว่า การใดๆ อันทำลงโดยชอบด้วยกฎหมายและด้วยใจสมัคร มุ่งโดยตรงต่อการผูกนิติสัมพันธ์ขึ้นระหว่างบุคคล...

ข้อสังเกต
จากมาตรา 149 จะเห็นได้ว่าองค์ประกอบของนิติกรรมมี 5 ประการ คือ
1. การแสดงเจตนา
2. ทำโดยชอบด้วยกฎหมาย
    \"\"\"
    
    cleaned = clean_thai_text(sample_ocr)
    parsed = parse_legal_layer(cleaned)
    
    import json
    print(json.dumps(parsed, ensure_ascii=False, indent=2))
